name: Simple Docker Image React

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag vansingco/simple-docker-react-dev:$(date +%s)
    - name: Test the project using docker image
      run: docker run vansingco/simple-docker-react-dev:$(date +%s) npm run test -- --coverage
